[workspace]
members = ["mason-core", "mason-android", "mason-ios", "mason-playground", "mason-c"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
debug = false
incremental = false
strip = true
debug-assertions = false
overflow-checks = false
